spring:
  datasource:
    url: jdbc:postgresql://localhost:5444/someschema
    username: something
    password: something
    platform: postgresql
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
crnk:
 pathPrefix: /crnk
server:
  port: 8120